name: NicknameChanger
version: 1.0
main: me.yourname.NicknameChanger
api-version: 1.21
description: Minecraft 1.21.6용 채팅 닉네임 변경 플러그인
author: FangLas
commands:
  setnick:
    description: 닉네임을 설정합니다.
    usage: /setnick <닉네임>
    permission: nicknamechanger.setnick
  resetnick:
    description: 닉네임을 초기화합니다.
    usage: /resetnick
    permission: nicknamechanger.resetnick
permissions:
  nicknamechanger.setnick:
    description: 닉네임을 설정할 수 있는 권한
    default: true
  nicknamechanger.resetnick:
    description: 닉네임을 초기화할 수 있는 권한
    default: true
